In [103]:
import pandas as pd
import numpy as np
import os
import glob

In [104]:
dfs = {
    os.path.basename(x).split('_')[0]: pd.read_csv(x, sep='\t')
    for x in glob.glob(os.path.join('fem_long_data', '*.tsv'))
}

In [105]:
display_results = pd.DataFrame(columns=[
    'Solution', 'w/ BC', 'Min. RL2E. (%)', 'Time to <5% RL2E. and 0.01 PDE residual (s)', 'Time to min. RL2E. (s)',
    'Residual (at 5% err)', 'Residual (at min err)'
])

for name in dfs:
    df = dfs[name]
    try:
        first_row = df[(df['rel_l2_val_error'] < 0.05) & (df['pde_residual'] < 0.01)].iloc[0]
        time_to_5p = first_row['training_time'].item()
        residual_5p = first_row['pde_residual'].item()
    except:
        time_to_5p = np.nan
        residual_5p = np.nan
    min_err = df['rel_l2_val_error'].min() * 100.0
    time_to_min_err = df[df['rel_l2_val_error'] <= df['rel_l2_val_error'].min()].iloc[0]['training_time'].item()
    residual_min_err = df[df['rel_l2_val_error'] <= df['rel_l2_val_error'].min()].iloc[0]['pde_residual'].item()
    info = {
        'Solution': name,
        'w/ BC': True,
        'Min. RL2E. (%)': min_err,
        'Time to <5% RL2E. and 0.01 PDE residual (s)': time_to_5p,
        'Time to min. RL2E. (s)': time_to_min_err,
        'Residual (at 5% err)': residual_5p,
        'Residual (at min err)': residual_min_err
    }
    display_results.loc[len(display_results)] = info
    
display_results['Solution'] = display_results['Solution'].map({'rw': 4, 'hopf': 3, 'sp': 2, 'pw': 1})
display_results = display_results.sort_values(by='Solution').reset_index(drop=True)

display_results

,Solution,w/ BC,Min. RL2E. (%),Time to <5% RL2E. and 0.01 PDE residual (s),Time to min. RL2E. (s),Residual (at 5% err),Residual (at min err)
0,1,True,0.414978,NaN,68.464817,NaN,0.234513
1,2,True,0.168375,NaN,267.164172,NaN,0.202945
2,3,True,0.070452,404.814654,85.274218,0.009962,0.014888
3,4,True,0.145622,NaN,96.537507,NaN,0.039967

In [106]:
print(display_results.to_markdown(index=False))

|   Solution | w/ BC   |   Min. RL2E. (%) |   Time to <5% RL2E. and 0.01 PDE residual (s) |   Time to min. RL2E. (s) |   Residual (at 5% err) |   Residual (at min err) |
|-----------:|:--------|-----------------:|----------------------------------------------:|-------------------------:|-----------------------:|------------------------:|
|          1 | True    |        0.414978  |                                       nan     |                  68.4648 |           nan          |               0.234513  |
|          2 | True    |        0.168375  |                                       nan     |                 267.164  |           nan          |               0.202945  |
|          3 | True    |        0.0704518 |                                       404.815 |                  85.2742 |             0.00996237 |               0.0148877 |
|          4 | True    |        0.145622  |                                       nan     |                  96.5375 |           nan          |               0.0399667 |

In [107]:
display_results = pd.DataFrame(columns=[
    'Solution', 'w/ BC', 'Min. RL2E. (%)', 'Time to <5% RL2E. (s)', 'Time to min. RL2E. (s)',
    'Residual (at 5% err)', 'Residual (at min err)'
])

for name in dfs:
    df = dfs[name]
    try:
        first_row = df[(df['rel_l2_val_error'] < 0.05)].iloc[0]
        time_to_5p = first_row['training_time'].item()
        residual_5p = first_row['pde_residual'].item()
    except:
        time_to_5p = np.nan
        residual_5p = np.nan
    min_err = df['rel_l2_val_error'].min() * 100.0
    time_to_min_err = df[df['rel_l2_val_error'] <= df['rel_l2_val_error'].min()].iloc[0]['training_time'].item()
    residual_min_err = df[df['rel_l2_val_error'] <= df['rel_l2_val_error'].min()].iloc[0]['pde_residual'].item()
    info = {
        'Solution': name,
        'w/ BC': True,
        'Min. RL2E. (%)': min_err,
        'Time to <5% RL2E. (s)': time_to_5p,
        'Time to min. RL2E. (s)': time_to_min_err,
        'Residual (at 5% err)': residual_5p,
        'Residual (at min err)': residual_min_err
    }
    display_results.loc[len(display_results)] = info
    
display_results['Solution'] = display_results['Solution'].map({'rw': 4, 'hopf': 3, 'sp': 2, 'pw': 1})
display_results = display_results.sort_values(by='Solution').reset_index(drop=True)

display_results

,Solution,w/ BC,Min. RL2E. (%),Time to <5% RL2E. (s),Time to min. RL2E. (s),Residual (at 5% err),Residual (at min err)
0,1,True,0.414978,68.464817,68.464817,0.234513,0.234513
1,2,True,0.168375,71.240415,267.164172,0.200718,0.202945
2,3,True,0.070452,5.084945,85.274218,0.017616,0.014888
3,4,True,0.145622,96.537507,96.537507,0.039967,0.039967

In [108]:
print(display_results.to_markdown(index=False))

|   Solution | w/ BC   |   Min. RL2E. (%) |   Time to <5% RL2E. (s) |   Time to min. RL2E. (s) |   Residual (at 5% err) |   Residual (at min err) |
|-----------:|:--------|-----------------:|------------------------:|-------------------------:|-----------------------:|------------------------:|
|          1 | True    |        0.414978  |                68.4648  |                  68.4648 |              0.234513  |               0.234513  |
|          2 | True    |        0.168375  |                71.2404  |                 267.164  |              0.200718  |               0.202945  |
|          3 | True    |        0.0704518 |                 5.08495 |                  85.2742 |              0.0176158 |               0.0148877 |
|          4 | True    |        0.145622  |                96.5375  |                  96.5375 |              0.0399667 |               0.0399667 |